<?php

namespace app\controllers;
namespace frontend\controllers;

use kartik\mpdf\Pdf;
use Yii;
use app\models\Empleado;
use app\models\Periodo;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\EmpleadoSearch;
use yii\filters\VerbFilter;
use yii\db\Query;


/**
 * EmpleadoController implements the CRUD actions for Empleado model.
 */
class EmpleadoController extends Controller
{   

    public function actionComprobante(){
        $model = new Periodo;
        $model1 = new Empleado;
        if ($model->load(Yii::$app->request->post()) && $model1->load(Yii::$app->request->post())) {
            $year = $model->year;
            $mes = $model->mes;
            $per = $model->dia;
            $tipo = $model->tipo;
            $cedula = $model1->cedula;

            $path = Yii::getAlias('@webroot') . '/uploads';
            //echo $path;
            $file = $path.'/'.$tipo.'/'.$year.'/'.$mes.'/'.$per.'/'.$cedula.'.pdf';
            //echo $file.'<br>';
            if (file_exists($file)) {
                Yii::$app->response->sendFile($file);
            }
            else {
                 throw new NotFoundHttpException('Uno de tus datos esta errado.');
            }
            //print_r($_POST);

        }
        return $this->render('comprobante', ['model' => $model, 'model1'=>$model1]);
    
    }
    public function actionCertificado(){
        
        $model = new Empleado();

        if ($model->load(Yii::$app->request->post())) {
            $cedula = $model->cedula;
            $clave = $model->clave;
            $connection = \Yii::$app->db;
            echo $cedula;
            $models = Empleado::find()->where('cedula = '.$cedula.'')->all();
            
            foreach ($models as $model) {
                echo 'Car name: ' . $model->nom_emp;
                echo '<br/>';
                echo 'Car color: ' . $model->cedula;

                if ( $model->clave == $clave){
                    
                    //GENERAR PDF PARA PROLUB
                    if ($model->empresa_ide_emp == 1){
                    $pdf = new Pdf([
                    'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
                    'content' => $this->renderPartial('prolub', ['model'=>$model]),
                    'options' => ['title' => 'Certificado Laboral','subject' => 'Prolub SA'],
                    'methods' => []
                    ]);
                    return $pdf->render();
                }
                else if ($model->empresa_ide_emp == 2){
                    $pdf = new Pdf([
                    'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
                    'content' => $this->renderPartial('opeco', ['model'=>$model]),
                    'options' => ['title' => 'Certificado Laboral','subject' => 'OPECO SAS'],
                    'methods' => []
                    ]);
                    return $pdf->render();
                }
            }
                else{
                    echo "no coincide";

                }
            }
        }
        else {
            return $this->render('certificado', [
                'model' => $model,
            ]);
        }
    }
public function actionPdf() {


    $pdf = new Pdf([
        'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
        'content' => $this->renderPartial('privacy'),
        'options' => [
            'title' => 'Privacy Policy - Krajee.com',
            'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
        ],
        'methods' => [
            'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
            'SetHeader' => ['Pragma: public'],
            'SetHeader' => ['Expires: 0'],
            'SetHeader' => ['Content-type: $content_type'],
            'SetHeader' => ['Cache-Control: private', FALSE],
            'SetHeader' => ['Cache-Control: must-revalidate, post-check=0, pre-check=0'],
            'SetHeader' => ['Content-Disposition: inline; filename=\"$filename\""'],
            'SetHeader' => ['Content-Transfer-Encoding: binary'],
            'SetHeader' => ['Content-Length' . filesize($path)],
            'SetFooter' => ['|Page {PAGENO}|'],
        ]
    ]);
    return $pdf->render();
}
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
            'class' => \yii\filters\AccessControl::className(),
            'only' => ['view', 'index', 'create', 'update', 'delete'],
            'rules' => [
                // deny all POST requests
                
                // allow authenticated users
                [
                    'allow' => true,
                    'actions' => ['view', 'index', 'create', 'update', 'delete'],
                    'roles' => ['@'],
                ],
                // everything else is denied
            ],
        ],
        ];
    }

    /**
     * Lists all Empleado models.
     * @return mixed
     */


    public function actionIndex()
    {
         $searchModel = new EmpleadoSearch();
       $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
       return $this->render('index', [
           'searchModel' => $searchModel, 
           'dataProvider' => $dataProvider,
       ]); 
    }

    /**
     * Displays a single Empleado model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Empleado model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Empleado();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ide_emp]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionC()
    {
        $model = new Empleado();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ide_emp]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Empleado model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->ide_emp]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Empleado model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Empleado model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Empleado the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Empleado::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
