<?php
if(isset($_POST['enviar'])){

        if (empty($_POST["name"]))
            {
                echo '<script type="text/javascript">alert("Digite su numero de identificación");</script>';
                echo "hola";
                echo '<center><br><a class="volver" href="http://nuestrared.prolub.com.co/pdf/form.php">Volver</a></center>';
            }
        else
            {
                if (empty($_POST["pass"]))
                    {
                        echo '<script type="text/javascript">alert("Digite su clave");</script>';   
                        echo '<center><br><a class="volver" href="http://nuestrared.prolub.com.co/pdf/form.php">Volver</a></center>';
                    }
                    else
                    {

    $pdf = new Pdf([
        'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
        'content' => $this->renderPartial('privacy'),
        //'content' => 'hola',
        'options' => [
            'title' => 'Privacy Policy - Krajee.com',
            'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
        ],
        'methods' => [
            'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
            //'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
            'SetHeader' => ['Pragma: public'],
            'SetHeader' => ['Expires: 0'],
            'SetHeader' => ['Content-type: $content_type'],
            'SetHeader' => ['Cache-Control: private', FALSE],
            'SetHeader' => ['Cache-Control: must-revalidate, post-check=0, pre-check=0'],
            'SetHeader' => ['Content-Disposition: inline; filename=\"$filename\""'],
            'SetHeader' => ['Content-Transfer-Encoding: binary'],
            'SetHeader' => ['Content-Length' . filesize($path)],
            'SetFooter' => ['|Page {PAGENO}|'],
        ]
    ]);
    return $pdf->render();
}
}}
?>